version: "3.2"

services:
  shopping-cart:
    image: cloudstateio/cloudstate-proxy-dev-mode:latest
    environment:
      USER_FUNCTION_HOST: shopping-cart-impl
      USER_FUNCTION_PORT: 8080
    depends_on:
      - shopping-cart-impl
    ports:
      - "9000:9000"

  shopping-cart-impl:
    image: vkorenev/shopping-cart:ts-0.1.0
    environment:
      HOST: shopping-cart-impl

  inventory:
    image: cloudstateio/cloudstate-proxy-dev-mode:latest
    environment:
      USER_FUNCTION_HOST: inventory-impl
      USER_FUNCTION_PORT: 8080
    depends_on:
      - inventory-impl
    ports:
      - "9001:9000"

  inventory-impl:
    image: vkorenev/inventory:ts-0.1.0
    environment:
      HOST: inventory-impl

  shopping-service:
    image: cloudstateio/cloudstate-proxy-dev-mode:latest
    environment:
      USER_FUNCTION_HOST: shopping-service-impl
      USER_FUNCTION_PORT: 8080
    depends_on:
      - shopping-service-impl
    ports:
      - "9002:9000"

  shopping-service-impl:
    image: vkorenev/shopping-service:ts-0.1
    environment:
      SHOPPING_CART_CLIENT_ADDRESS: shopping-cart:9000
      PRODUCT_INVENTORY_CLIENT_ADDRESS: inventory:9000
