# Deployment spec for our shopping cart event sourced function
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: inventory
spec:
  # Datastore configuration
  storeConfig:
    database: inventory
    statefulStore:
      # Name of a deployed Datastore to use.
      name: shopping-store
  containers:
    - image: vkorenev/inventory:java-0.2
      name: inventory
