# Route for shopping cart app
apiVersion: cloudstate.io/v1alpha1
kind: Route
metadata:
  name: "shopping-routes"
spec:
  http:
  - name: "shopping-cart-routes"
    match:
    - uri:
        prefix: "/com.example.shoppingcart.ShoppingCart/"
    route:
      service: shopping-cart
  - name: "inventory-routes"
    match:
    - uri:
        prefix: "/com.example.inventory.Inventory/"
    route:
      service: inventory
  - name: "shopping-service-routes"
    match:
    - uri:
        prefix: "/com.example.shoppingservice.ShoppingService/"
    route:
      service: shopping-service
  - name: "frontend-routes"
    match:
    - uri:
        prefix: "/"
    route:
      service: frontend      

